version: '3.3'
services:
  streamlit-app:
    build:
      context: .  # Use o diret贸rio atual como contexto para encontrar o Dockerfile
    ports:
      - "8501:8501"  # Mapeie a porta do container para a porta do host
    volumes:
      - ./app:/app  # Mapeie o diret贸rio de c贸digo local para o diret贸rio de trabalho no container
